chore: update CSV broken links
submariner-io/submariner-operator pull request #1014
Opened 2020-12-23 10:20 UTC by SteveMattar

Signed-off-by: Steve Mattar <smattar@redhat.com>

2020-12-23 11:04 UTC, SteveMattar commented
this PR should find broken links in the future:
https://github.com/submariner-io/submariner-operator/pull/1013

2020-12-23 14:58 UTC, nyechiel approved these changes

2020-12-24 12:39 UTC, skitt approved these changes

2021-01-05 16:34 UTC, skitt requested changes
This shouldn’t be merged until we figure out why #1013 isn’t failing without it.

2021-01-13 14:04 UTC, skitt approved these changes

2021-01-13 14:05 UTC, merged