Publish subctl for devel and release-xxx
submariner-io/submariner-operator pull request #1068
Opened 2021-02-05 16:32 UTC by mangelajo

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2021-02-05 16:52 UTC, tpantelis requested changes

2021-02-05 16:52 UTC, tpantelis commented on .github/workflows/subctl_bleeding_edge.yml
> +      - master
?

```suggestion
      - devel
```

2021-02-05 16:54 UTC, mangelajo commented on .github/workflows/subctl_bleeding_edge.yml
> +      - master
oh good catch ':D

2021-02-05 16:55 UTC, mangelajo commented on .github/workflows/subctl_bleeding_edge.yml
> +      - master
Done.

2021-02-05 17:20 UTC, tpantelis approved these changes

2021-02-07 17:03 UTC, nyechiel approved these changes

2021-02-08 08:32 UTC, merged