Deploy CRDs only as required by components
submariner-io/submariner-operator pull request #1109
Opened 2021-02-24 14:02 UTC by skitt

We no longer need the Submariner CRDs all the time; only when
connectivity is required. Service-discovery-only deployments shouldn’t
have the Submariner CRDs.

The operator however needs the CRDs for resources it manages; this
includes service discovery, so that CRD is added when setting up the
operator.

This patch distinguishes deployments by components, and only sets up
the relevant CRDs. It includes a stub Globalnet component which
shouldn’t be used as such but will be fleshed out later.

Fixes: #1098
Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-02-24 15:36 UTC, tpantelis requested changes

2021-02-24 15:36 UTC, tpantelis commented on pkg/subctl/datafile/datafile.go
> +	// We attempt to access a Submariner object; if we can’t find this, we know we still connected
?

```suggestion
	// We attempt to access a Submariner object; if we can’t find this, we know we can still connect
```

2021-02-24 15:36 UTC, tpantelis commented on pkg/broker/ensure.go
> +					return fmt.Errorf("error setting up the engine requirements: %s", err)
```suggestion
					return fmt.Errorf("error setting up the connectivity requirements: %s", err)
```

2021-02-24 15:36 UTC, tpantelis commented on pkg/broker/ensure.go
> +					return fmt.Errorf("error setting up the lighthouse requirements: %s", err)
```suggestion
					return fmt.Errorf("error setting up the service discovery requirements: %s", err)
```

2021-02-24 15:36 UTC, tpantelis commented on pkg/broker/ensure.go
> +					return fmt.Errorf("error setting up the lighthouse requirements: %s", err)
```suggestion
					return fmt.Errorf("error setting up the globalnet requirements: %s", err)
```

2021-03-02 06:24 UTC, vthapar approved these changes

2021-03-03 16:49 UTC, nyechiel commented
@skitt this one needs some love :)

2021-03-05 12:54 UTC, mangelajo approved these changes

2021-03-05 14:28 UTC, tpantelis approved these changes

2021-03-05 15:58 UTC, tpantelis commented
The unit test job keeps failing - make fails with exit status 2 but I don't see a reason for it - all the tests pass.

2021-03-05 18:02 UTC, dfarrell07 commented
> The unit test job keeps failing - make fails with exit status 2 but I don't see a reason for it - all the tests pass.

I also don't see a PR here or in Shipyard that could have caused this.

It seems to have started just a few hours ago.

https://github.com/submariner-io/submariner-operator/actions/workflows/unit.yml

2021-03-05 18:55 UTC, tpantelis commented
> > The unit test job keeps failing - make fails with exit status 2 but I don't see a reason for it - all the tests pass.
> 
> I also don't see a PR here or in Shipyard that could have caused this. I don't see similar failures in other repos.
> 
> It seems to have started just a few hours ago.
> 
> https://github.com/submariner-io/submariner-operator/actions/workflows/unit.yml

yeah it mysteriously started. One difference between the failing runs and the successful runs prior is that the former have this near the end just prior to failing:

```
[submariner-operator]$ uname
make: *** [/opt/shipyard/Makefile.inc:100: unit] Error 1
```

Not sure of the significance or where that is coming from.

2021-03-08 17:16 UTC, dfarrell07 approved these changes

2021-03-09 13:01 UTC, merged