Use subctl & submariner-operator Version from $VERSION
submariner-io/submariner-operator pull request #1267
Opened 2021-04-20 12:34 UTC by mangelajo

VERSION defaults to CALCULATED_VERSION if nothing is provided
for make.

For example:

  `make build-cross` will result in binaries containing devel-xxxxx
as version, while VERSION=v0.9.0 make build-cross will result in
binaries containing v0.9.0 as version.

VERSION env var is passed down from the release scripts here:
https://github.com/submariner-io/releases/pull/124/files

Fixes-Issue: #1266

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2021-04-20 12:36 UTC, tpantelis approved these changes

2021-04-20 12:44 UTC, mkolesnik requested changes
Looks fine to me, but I'd like to know what @skitt thinks since he originally did #527 which introduced this usage.

Also you left the comment - https://github.com/submariner-io/submariner-operator/pull/1267/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R108

2021-04-20 12:44 UTC, mangelajo commented
@skitt, @mkolesnik wanted you to have an eye on this when you are back, since we are partially reverting https://github.com/submariner-io/submariner-operator/pull/527/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R69

Because of #1266 && https://github.com/submariner-io/releases/pull/124/files

2021-04-20 12:45 UTC, mangelajo commented
> Looks fine to me, but I'd like to know what @skitt thinks since he originally did #527 which introduced this usage.

xinx Although I think it's not a big of a deal, and... that we should merge it if this were to delay release in any way.

2021-04-20 12:46 UTC, mkolesnik commented
> > Looks fine to me, but I'd like to know what @skitt thinks since he originally did #527 which introduced this usage.
> 
> xinx Although I think it's not a big of a deal, and... that we should merge it if this were to delay release in any way.

skitt should be back next week, so i reckon hell take a look before this becomes a problem

2021-04-20 12:47 UTC, mangelajo commented
Behaviour after this patch,

With VERSION not set:
```
[submariner-operator]$ ldflags=-s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=devel-394aaf9 		   -X=github.com/submariner-io/submariner-operator/pkg/versions.DefaultSubmarinerOperatorVersion=devel
[submariner-operator]$ CGO_ENABLED=0 go build -trimpath -ldflags -s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=devel-394aaf9 		   -X=github.com/submariner-io/submariner-operator/pkg/versions.DefaultSubmarinerOperatorVersion=devel -o bin/subctl-devel-394aaf9-linux-amd64 ./pkg/subctl/main.go
```

with VERSION set to v0.9.1:
```
[submariner-operator]$ ldflags=-s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=v0.9.1 		   -X=github.com/submariner-io/submariner-operator/pkg/versions.DefaultSubmarinerOperatorVersion=devel
[submariner-operator]$ CGO_ENABLED=0 go build -trimpath -ldflags -s -w -X github.com/submariner-io/submariner-operator/pkg/version.Version=v0.9.1 		   -X=github.com/submariner-io/submariner-operator/pkg/versions.DefaultSubmarinerOperatorVersion=devel -o bin/subctl-v0.9.1-linux-amd64 ./pkg/subctl/main.go
```

2021-04-20 12:47 UTC, mangelajo commented
> skitt should be back next week, so i reckon he'll take a look before this becomes a problem

I hope he doesn't have my PTO recovery time, lol

2021-04-26 13:15 UTC, skitt requested changes
The way we use the various versions has changed since #527, and I think we need to review the overall situation; but given the current state of affairs this seems fine to me. There is an additional change to make however: please remove the comment in line 109.

2021-04-26 14:06 UTC, mkolesnik approved these changes

2021-04-26 14:25 UTC, skitt approved these changes

2021-04-26 15:09 UTC, merged