subctl gather: reconcile Submariner/ServiceDiscovery installed
submariner-io/submariner-operator pull request #1283
Opened 2021-04-21 14:54 UTC by tpantelis

Obtain both resources and use/skip functionality where appropriate.

2021-04-22 08:52 UTC, mangelajo requested changes
Couple of nits (some pre-existing)

2021-04-22 08:52 UTC, mangelajo commented on pkg/subctl/cmd/gather/resource.go
>  		dataString = strings.ReplaceAll(dataString, info.Submariner.Spec.BrokerK8sApiServer, "##redeacted-api-server##")
```suggestion
		dataString = strings.ReplaceAll(dataString, info.Submariner.Spec.BrokerK8sApiServer, "##redacted-api-server##")
```

2021-04-22 08:52 UTC, mangelajo commented on pkg/subctl/cmd/gather/resource.go
> +		dataString = strings.ReplaceAll(dataString, info.ServiceDiscovery.Spec.BrokerK8sApiServer, "##redeacted-api-server##")
```suggestion
		dataString = strings.ReplaceAll(dataString, info.ServiceDiscovery.Spec.BrokerK8sApiServer, "##redacted-api-server##")
```

2021-04-22 16:49 UTC, Jaanki approved these changes

2021-04-23 05:18 UTC, vthapar approved these changes

2021-04-23 08:04 UTC, mangelajo approved these changes

2021-04-23 08:25 UTC, merged