Remove misleading OVN CNI not supported msg
submariner-io/submariner-operator pull request #1291
Opened 2021-04-22 12:22 UTC by vthapar

OVN CNI is now handled explicitly in its own function instead of generic
`CNIResources`. Remove OVN from CNI type check in `CNIResources`

Fixes #1288

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

2021-04-22 13:08 UTC, mangelajo commented on pkg/subctl/cmd/gather/cni.go
> -			case typeOvn:
let's keep the "typeOvn: " with no action, otherwise we will get the typeUnknown "failure".

2021-04-22 13:08 UTC, mangelajo requested changes
let's keep the "typeOvn: " with no action, otherwise we will get the typeUnknown "failure".

2021-04-22 13:36 UTC, tpantelis approved these changes

2021-04-23 10:36 UTC, mangelajo approved these changes

2021-04-23 13:19 UTC, merged