Fix broken `--kubecontext`
submariner-io/submariner-operator pull request #1355
Opened 2021-05-11 13:50 UTC by mkolesnik

Reverted it to use it's own variable (which works fine).

Also renamed the function names so its easy to distinguish between the
different functionality.

Resolves: #1351 

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-05-11 13:57 UTC, tpantelis requested changes, later dismissed
couple nits

2021-05-11 13:57 UTC, tpantelis commented on pkg/subctl/cmd/root.go
> +func addKubecontextFlag(cmd *cobra.Command) {
```suggestion
func addKubeContextFlag(cmd *cobra.Command) {
```

2021-05-11 13:57 UTC, tpantelis commented on pkg/subctl/cmd/root.go
> +func addKubecontextMultiFlag(cmd *cobra.Command) {
```suggestion
func addKubeContextMultiFlag(cmd *cobra.Command) {
```

2021-05-12 05:27 UTC, mkolesnik commented
Be sure to squash when merging

2021-05-12 12:55 UTC, dfarrell07 approved these changes

2021-05-12 13:12 UTC, vthapar commented
This will reaquire changes to documentation for `subctl gather` which uses `--kubecontexts`.

2021-05-12 13:13 UTC, skitt approved these changes

2021-05-12 14:12 UTC, mkolesnik commented
> This will reaquire changes to documentation for `subctl gather` which uses `--kubecontexts`.

WDYM? That flag still exists - https://github.com/submariner-io/submariner-operator/pull/1355/files#diff-8a58275c37bca775e6338952d361c5a6f84bfc2956093290bb661ed575c7c9d0R82

2021-05-18 08:32 UTC, merged

2021-05-18 10:02 UTC, vthapar commented
> > This will reaquire changes to documentation for `subctl gather` which uses `--kubecontexts`.
> 
> WDYM? That flag still exists - https://github.com/submariner-io/submariner-operator/pull/1355/files#diff-8a58275c37bca775e6338952d361c5a6f84bfc2956093290bb661ed575c7c9d0R82

Nvm, I missed that.