Register Globalnet v2.0 CRDs
submariner-io/submariner-operator pull request #1381
Opened 2021-05-25 15:12 UTC by sridhargaddam

In this PR, we register Globalnet V2.0 CRDs like ClusterGlobalnetEgressIP,
GlobalEgressIP and GlobalIngressIP.

Fixes issue: https://github.com/submariner-io/submariner/issues/1358
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-05-25 15:19 UTC, tpantelis approved these changes

2021-05-26 11:15 UTC, SteveMattar requested changes
@sridhargaddam  you should escape the tilde character

yamls2go.go:

```suggestion
	re := regexp.MustCompile("`([^`]*)`")
	reNS := regexp.MustCompile(`(?s)\s*namespace:\s*\$\(SA_NAMESPACE\)\s*`)
	reTilde := regexp.MustCompile("`")

	for _, f := range files {
		_, err = out.WriteString("\t" + constName(f) + " = `")
		panicOnErr(err)

		fmt.Println(f)
		contents, err := ioutil.ReadFile(path.Join(yamlsDirectory, f))
		panicOnErr(err)

		_, err = out.Write(
			re.ReplaceAll(
				reNS.ReplaceAll(
					reTilde.ReplaceAll(contents, []byte("`" + "`")),
					[]byte("\n")),
				[]byte("` + \"`$1`\" + `")))
		panicOnErr(err)

		_, err = out.WriteString("`\n")
		panicOnErr(err)
	}
	_, err = out.WriteString(")\n")
	panicOnErr(err)

	err = out.Close()
	panicOnErr(err)
}
```

2021-05-26 11:53 UTC, sridhargaddam commented
Thanks @SteveMattar

2021-05-26 14:01 UTC, SteveMattar approved these changes

2021-05-26 15:01 UTC, merged