Refactor restconfig parts to its own module
submariner-io/submariner-operator pull request #1404
Opened 2021-06-04 10:58 UTC by mangelajo

Moves the restconfig functions into its module, so later
we can continue moving each command into separate directories
without causing circular dependencies to the base cmd directory
functions.

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2021-06-04 11:00 UTC, mangelajo commented
I started a series of cleanups into subctl to allow us separation of commands into their own directories. This changes no functionality/implementation, just moves it into a separate dir.

2021-06-04 12:16 UTC, tpantelis commented
I've also done some refactoring [here](https://github.com/submariner-io/submariner-operator/pull/1364), which has been awaiting review for a while now.  There's maybe some overlap with this one.

2021-06-04 12:57 UTC, mangelajo commented
> I've also done some refactoring [here](https://github.com/submariner-io/submariner-operator/pull/1364), which has been awaiting review for a while now. There's maybe some overlap with this one.

Oh, sorry about that. Let's review & merge yours, then we can continue.

2021-06-04 13:01 UTC, mangelajo commented
Let's focus on this one here first: https://github.com/submariner-io/submariner-operator/pull/1364

2021-06-06 06:47 UTC, mkolesnik requested changes, later dismissed

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetRestConfig(kubeConfigPath, kubeContext string) (*rest.Config, error) {
```suggestion
func ForCluster(kubeConfigPath, kubeContext string) (*rest.Config, error) {
```

Would look better `restconfig.ForCluster`.
Also the module is already called `restconfig` so repeating it here is stuttering :)

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetMultipleRestConfigs(kubeConfigPath string, kubeContexts []string) ([]RestConfig, error) {
```suggestion
func ForClusters(kubeConfigPath string, kubeContexts []string) ([]RestConfig, error) {
```

Would look better `restconfig.ForClusters`.
Also the module is already called `restconfig` so repeating it here is stuttering :)

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetBrokerRestConfigAndNamespace(submariner *v1alpha1.Submariner,
```suggestion
func ForBroker(submariner *v1alpha1.Submariner,
```

Would look better restconfig.ForBroker.
Also the module is already called restconfig so repeating it here is stuttering :)

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetClientConfigAndClusterName(rules *clientcmd.ClientConfigLoadingRules, overrides *clientcmd.ConfigOverrides) (RestConfig, error) {
```suggestion
func clientConfigAndClusterName(rules *clientcmd.ClientConfigLoadingRules, overrides *clientcmd.ConfigOverrides) (RestConfig, error) {
```

No need to export it, it's only used internally

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetClients(config *rest.Config) (dynamic.Interface, kubernetes.Interface, error) {
```suggestion
func Clients(config *rest.Config) (dynamic.Interface, kubernetes.Interface, error) {
```

https://golang.org/doc/effective_go#Getters

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetClusterNameFromContext(rawConfig api.Config, overridesContext string) *string {
```suggestion
func ClusterNameFromContext(rawConfig api.Config, overridesContext string) *string {
```

https://golang.org/doc/effective_go#Getters

2021-06-06 06:47 UTC, mkolesnik commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +	return utils.GetClientConfig(kubeConfigPath, kubeContext)
You should move the methods from utils here since that makes more sense now that `restconfig` is its own module

2021-06-17 16:08 UTC, mangelajo commented on pkg/subctl/cmd/utils/restconfig/restconfig.go
> +func GetClusterNameFromContext(rawConfig api.Config, overridesContext string) *string {
:rocket:

2021-06-17 16:25 UTC, mangelajo commented
I have applied all the comments (thanks @mkolesnik !) and rebased on top of the previous refactor @tpantelis .

Have an eye! :)

2021-06-17 16:27 UTC, Jaanki approved these changes

2021-06-18 10:02 UTC, mangelajo commented
@skitt ping ^  :-)

2021-06-18 13:33 UTC, tpantelis approved these changes

2021-06-20 06:39 UTC, maayanf24 approved these changes

2021-06-22 12:08 UTC, merged