Move gathered resources to a SummaryInfo struct
submariner-io/submariner-operator pull request #1420
Opened 2021-06-15 13:09 UTC by skitt

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-06-15 13:19 UTC, Jaanki approved these changes

2021-06-15 13:24 UTC, tpantelis reviewed
Looks good.

2021-06-15 13:24 UTC, tpantelis commented on pkg/subctl/cmd/gather/logs.go
> +var podLogInfo LogInfo
I assume these globals will be removed as well.

2021-06-18 11:34 UTC, mangelajo approved these changes
oops sorry for the conflicts but it looks good.

2021-06-18 12:46 UTC, tpantelis requested changes
Is the intention to merge this PR or https://github.com/submariner-io/submariner-operator/pull/1260?

2021-06-18 12:46 UTC, tpantelis commented on pkg/subctl/cmd/gather/logs.go
> +func writeLogToFile(data, podName string, info Info, fileExtension string) (*string, error) {
There's really no reason to return a string pointer - if an error occurs return empty string. 

```suggestion
func writeLogToFile(data, podName string, info Info, fileExtension string) (string, error) {
```

2021-06-22 08:57 UTC, skitt commented
Merged into #1260.

2021-06-22 08:57 UTC, closed without merging