Change subctl devel release to use GH CLI
submariner-io/submariner-operator pull request #1450
Opened 2021-06-28 12:00 UTC by mkolesnik

Resolves: #1413

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2021-06-28 12:12 UTC, skitt requested changes
A minor tweak...

2021-06-28 12:12 UTC, skitt commented on .github/workflows/release_subctl_devel.yml
> +          sudo dpkg -i /tmp/gh.deb
```suggestion
          sudo apt install /tmp/gh.deb
```

to deal with dependencies if that’s ever necessary.

2021-06-28 16:08 UTC, mangelajo approved these changes
Leaving my +1 for after when @skitt comments are handled.

2021-06-29 08:14 UTC, mkolesnik commented
Make sure to quash when merging

2021-06-29 08:14 UTC, skitt approved these changes

2021-06-29 08:41 UTC, merged