Fix usage of kubeconfig flag in subctl verify
submariner-io/submariner-operator pull request #1475
Opened 2021-07-08 10:21 UTC by maayanf24

1. send kubeconfig flag to test framework so it will not be ignored
2. use a unique help text to kubecontexts flag when called from subctl
   verify

Fixes issue #1448

Signed-off-by: Maayan Friedman <maafried@redhat.com>

2021-07-08 11:57 UTC, tpantelis requested changes

2021-07-08 11:57 UTC, tpantelis commented on pkg/subctl/cmd/root.go
> +			"If none specified, all contexts referenced by kubeconfig are used"
```suggestion
		usage = "comma-separated list of kubeconfig contexts to use.\n" +
			"If none specified, all contexts referenced by the kubeconfig are used"
```

2021-07-08 11:57 UTC, tpantelis commented on pkg/subctl/cmd/verify.go
> +	AddKubeContextMultiFlag(verifyCmd, "comma separated list of kubeconfig contexts to use, must specified 2 contexts.")
```suggestion
	AddKubeContextMultiFlag(verifyCmd, "comma separated list of exactly two kubeconfig contexts to use.")
```

2021-07-08 15:05 UTC, skitt approved these changes
Tested locally in various combinations, everything works as expected.

2021-07-09 08:29 UTC, mangelajo approved these changes

2021-07-09 08:29 UTC, mangelajo commented on pkg/subctl/cmd/verify.go
> +	AddKubeContextMultiFlag(verifyCmd, "comma separated list of kubeconfig contexts to use, must specified 2 contexts.")
```suggestion
	AddKubeContextMultiFlag(verifyCmd, "comma separated list of kubeconfig contexts to use, 2 contexts must be specified.")
```

2021-07-13 04:00 UTC, tpantelis approved these changes

2021-07-13 05:12 UTC, merged