Support microshift deployments, with no dns operator
submariner-io/submariner-operator pull request #1503
Opened 2021-07-21 09:27 UTC by mangelajo

MicroShift[1] uses openshift coredns images, but it doesn't
enable the dns operator for footprint reasons, this means
that we need to patch the Corefile manually like for
vanilla k8s+coredns, but in the right namespaces.

Also MicroShift doesn't use the :53 port, but :5353, listening
on two ports doesn't work ok, we detect the existing Corefile
listening port, to use the specific port already being used,
defaulting to 53.

[1] https://github.com/redhat-et/microshift

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2021-07-22 10:07 UTC, mangelajo commented
@vthapar updated the patch with the extra test cases commented over slack :)

2021-07-22 11:33 UTC, vthapar requested changes, later dismissed
minor nit, rest looks good

2021-07-22 11:33 UTC, vthapar commented on controllers/servicediscovery/servicediscovery_controller_test.go
> +		When("no standard port is found and the coreconfig was already modified", func() {
```suggestion
		When("non-standard port is found and the coreconfig was already modified", func() {
```

2021-07-22 11:33 UTC, vthapar commented on controllers/servicediscovery/servicediscovery_controller_test.go
> +			When("no standard port is found and Coreconfig was not modified (OCP coreconfig)", func() {
```suggestion
			When("non-standard port is found and Coreconfig was not modified (OCP coreconfig)", func() {
```

2021-07-26 14:56 UTC, mangelajo commented on controllers/servicediscovery/servicediscovery_controller_test.go
> +		When("no standard port is found and the coreconfig was already modified", func() {
Done :)

2021-07-27 13:43 UTC, vthapar approved these changes

2021-07-27 14:34 UTC, tpantelis approved these changes

2021-07-27 15:09 UTC, merged