Limit cluster-id to 63 chars while joining a cluster
submariner-io/submariner-operator pull request #1518
Opened 2021-07-30 13:57 UTC by sridhargaddam

ClusterID is now stored as a label on the endpoint object when its
pushed to the Broker. K8s restricts the label values to 63 chars.
So adding the corresponding check.

Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-08-01 00:39 UTC, tpantelis requested changes

2021-08-01 00:39 UTC, tpantelis commented on pkg/subctl/cmd/join.go
> +			" value of 63 chars", clusterID, len(clusterID))
```suggestion
		return false, fmt.Errorf("The cluster ID %q has a length of %d characters which exceeds the maximum supported length of 63", clusterID, len(clusterID))
```

2021-08-02 13:12 UTC, skitt approved these changes

2021-08-02 13:26 UTC, tpantelis approved these changes

2021-08-02 13:50 UTC, merged