Rename release subctl devel job to cutting edge
submariner-io/submariner-operator pull request #1543
Opened 2021-08-13 12:26 UTC by tpantelis

When the release process replaces 'devel' with the release tag name,
the job fails b/c the tag name contains a '.' which is an invalid char.
So use 'cutting-edge' in the job name instead of 'devel'.'.

Fixes https://github.com/submariner-io/releases/issues/201

2021-08-13 12:29 UTC, tpantelis commented on .github/workflows/release_subctl_devel.yml
> -      - release-*
This doesn't seem necessary since `devel` is replaced by the actual release branch name when the branch is created.

2021-08-16 15:40 UTC, dfarrell07 requested changes
I don't understand why this fixes the issue of the stable branch name having a dot. The issue isn't "devel" I think, it's what we're replacing it with ("release-0.10"). As I understand it, this would just make the release automation fail to rename the job (it would look for devel, but now it's cutting-edge).

In general, I think we should be trying to standardize on naming things "devel" instead of mix of mostly-devel and a few "cutting-edge".

2021-08-16 16:08 UTC, tpantelis commented
> I don't understand why this fixes the issue of the stable branch name having a dot. The issue isn't "devel" I think, it's what we're replacing it with ("release-0.10"). 

Yes

> As I understand it, this would just make the release automation fail to rename the job (it would look for devel, but now it's cutting-edge).
> In general, I think we should be trying to standardize on naming things "devel" instead of mix of mostly-devel and a few "cutting-edge".

It does a simple search and replace of "devel" with the release branch name throughout the entire _.github/workflow_ directory. The resulting invalid name for this job is a side-effect of that. One option is to modify the release automation so it doesn't replace this instance of "devel". But, AFAIK, the name of the GH job doesn't really matter and doesn't need to reflect the actual branch name so the simplest thing to do is just to remove "devel" from the job name. To me, `cutting-edge` seems appropriate since the job creates the "Cutting Edge" release of the branch. Also the workflow name contains "Devel" which isn't replaced which is inconsistent.

2021-08-16 20:13 UTC, dfarrell07 commented
If the goal is to make this workflow unrelated to devel, something that applies to all branches, then let's call it something like "release-subctl-update". The actual difference between this workflow and the "release-subctl" workflow is that this one updates an existing release vs creating a new one.

2021-08-17 01:05 UTC, tpantelis commented
> If the goal is to make this workflow unrelated to devel, something that applies to all branches without a rename, then let's call it something like "release-subctl-update". The actual difference between this workflow and the "release-subctl" workflow is that this one updates an existing release vs creating a new one.

The goal is to fix the issue of the invalid job name by renaming it to not contain "devel". I'm not picky as to what we name it - "update" sounds fine to me. Let's see what others  (@skitt @mkolesnik ) think.

2021-08-17 13:16 UTC, skitt requested changes

2021-08-17 13:16 UTC, skitt commented on .github/workflows/release_subctl_cutting_edge.yml
> +name: Release Subctl Cutting Edge
```suggestion
name: Release Subctl devel
```

2021-08-17 13:16 UTC, skitt commented on .github/workflows/release_subctl_cutting_edge.yml
> +  release-subctl-cutting-edge:
```suggestion
  release-subctl-on-push:
```

2021-08-17 14:01 UTC, dfarrell07 approved these changes

2021-08-18 08:17 UTC, mangelajo approved these changes

2021-08-20 07:52 UTC, skitt approved these changes

2021-08-20 08:40 UTC, merged