Move broker ns creation to apis
submariner-io/submariner-operator pull request #1560
Opened 2021-09-07 12:35 UTC by Jaanki

....so that submariner-addon can use it.

Signed-off-by: Jaanki <jchhatba@redhat.com>

2021-09-07 14:17 UTC, tpantelis requested changes

2021-09-07 14:17 UTC, tpantelis commented on apis/submariner/manifests/namespace.go
> +}
This is simply a direct wrapper for the passed clientset,.  I don't think this function is really necessary and certainly  not as API to import from the add-on.

2021-09-07 14:40 UTC, skitt requested changes
There already is a public API for broker creation: the `Broker` CRD. To move broker namespace creation to the operator, we shouldn’t need any changes to the operator itself; the addon can be changed to create a `Broker` object as appropriate.

2021-09-08 09:19 UTC, Jaanki commented
> There already is a public API for broker creation: the `Broker` CRD. To move broker namespace creation to the operator, we shouldn’t need any changes to the operator itself; the addon can be changed to create a `Broker` object as appropriate.

That would require installing submariner-operator on hub cluster. Are we okay with that dependency? Currently submariner-addon installs submariner-operator on managedclusters but not on the hub cluster.

2021-09-29 15:34 UTC, closed without merging