Cloud prepare support for generic k8s clusters
submariner-io/submariner-operator pull request #1585
Opened 2021-09-29 15:11 UTC by sridhargaddam

This PR includes support for labelling worker nodes as
Submariner gateway nodes on generic k8s clusters.

Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-09-29 15:23 UTC, tpantelis requested changes

2021-09-29 15:23 UTC, tpantelis commented on pkg/subctl/cmd/cloud/cleanup/generic.go
> +		Long:  "This command cleans up a K8s cluster after Submariner uninstallation.",
```suggestion
		Long:  "This command cleans up Submariner components in a cluster after Submariner uninstallation.",
```

2021-09-29 15:23 UTC, tpantelis commented on pkg/subctl/cmd/cloud/cleanup/generic.go
> +		Short: "Clean up a k8s cluster",
```suggestion
		Short: "Cleans up a cluster after Submariner uninstallation",
```

2021-09-29 15:23 UTC, tpantelis commented on pkg/subctl/cmd/cloud/prepare/generic.go
> +		Short: "Prepare a generic K8s Cluster for Submariner",
```suggestion
		Short: "Prepares a generic cluster for Submariner",
```

2021-09-29 15:23 UTC, tpantelis commented on pkg/subctl/cmd/cloud/prepare/generic.go
> +		Long:  "This command prepares the K8s cluster for Submariner installation.",
```suggestion
		Long:  "This command prepares a generic cluster for Submariner installation.",
```

2021-10-05 12:06 UTC, tpantelis approved these changes

2021-10-05 13:09 UTC, aswinsuryan approved these changes

2021-10-05 13:52 UTC, skitt approved these changes

2021-10-05 13:52 UTC, merged