Remove phony prerequisites from the build target
submariner-io/submariner-operator pull request #1609
Opened 2021-10-11 16:26 UTC by skitt

See individual commits for details. The result of this PR is that two successive `make build` invocations won’t result in two rebuilds: the second invocation will see that it has nothing to do.

2021-10-11 16:32 UTC, skitt commented
Ah, this needs to use the updated vendoring support from Shipyard.

2021-10-13 06:22 UTC, mkolesnik requested changes
Thanks, some suggestions

2021-10-13 06:22 UTC, mkolesnik commented on Makefile
> +generate-embeddedyamls: pkg/subctl/operator/common/embeddedyamls/yamls.go
Can't this target be dropped then? It's only used in operator and I doubt anyone is running it manually.

Also this line is the same as 171.

2021-10-13 06:22 UTC, mkolesnik commented on Makefile
> +manifests: generate $(CONTROLLER_GEN) $(VENDOR_MODULES)
```suggestion
manifests: $(CONTROLLER_DEEPCOPY) $(CONTROLLER_GEN) $(VENDOR_MODULES)
```

2021-10-13 06:22 UTC, mkolesnik commented on Makefile
>  ci: generate-embeddedyamls golangci-lint markdownlint unit build images
```suggestion
ci: $(EMBEDDED_YAMLS) golangci-lint markdownlint unit build images
```

2021-10-13 06:22 UTC, mkolesnik commented on Makefile
> +generate: $(CONTROLLER_DEEPCOPY)
I reckon it's the same for this target, though I might be wrong

2021-11-04 12:04 UTC, mkolesnik approved these changes

2021-11-04 12:25 UTC, tpantelis approved these changes

2021-11-10 12:15 UTC, dfarrell07 approved these changes

2021-11-16 09:40 UTC, merged