Update K8s versions: drop 1.17/1.18, add 1.21/1.22
submariner-io/submariner-operator pull request #1627
Opened 2021-10-19 09:46 UTC by skitt

1.17 and 1.18 have reached EOL.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-10-19 11:29 UTC, Jaanki approved these changes

2021-10-19 12:03 UTC, tpantelis approved these changes

2021-10-19 12:58 UTC, mkolesnik commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
I thought line 18 was the newest?

2021-10-19 13:00 UTC, mkolesnik requested changes

2021-10-19 13:00 UTC, mkolesnik commented on .github/workflows/flake_finder.yml
>              globalnet: 'globalnet'
```suggestion
```

These lines are redundant now

2021-10-19 15:42 UTC, skitt commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
Isn’t that the default?

2021-10-20 15:30 UTC, dfarrell07 approved these changes

2021-10-25 21:54 UTC, dfarrell07 commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
This does highlight that commit/PR titles are a bit confusing, as the E2E default is actually unchanged at 1.20. We're also adding coverage for both 1.21 and 1.22. Something like "Add E2E for K8s 1.21-22, drop 1.17-18" might be more clear.

2021-10-26 07:48 UTC, mkolesnik commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
I think if you just list all the version here explicitly, GHA is smart enough not to run the "deault" twice.

2021-10-26 14:57 UTC, dfarrell07 commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
I may not understand what you're saying @mkolesnik. Adding K8s versions in `include`s gives jobs with only the K8s version non-default. The default K8s version is used in all the jobs defined by the matrix of the other params. Adding another `1.20` include would duplicate the job in the main matrix that uses all defaults.

2021-10-28 11:14 UTC, mkolesnik commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
> Adding another `1.20` include would duplicate the job in the main matrix that uses all defaults.

That's what I mean, it won't. GH is smart enough not to duplicate it.

However if we have all versions listed explicitly, we won't have to edit this list (or forget to) when we change the `1.20` default to some other version.

Hope this is clearer :)

2021-10-28 14:57 UTC, dfarrell07 commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
Ah okay, I see the underlying idea now. I hear you regarding that helping maintenance in a way, but I also (as you see) find it confusing to define duplicate jobs but rely on GHAs to not run them multiple times. An inline comment could mitigate that, though.

If we do this strategy, I guess it would be least-confusing to do it consistently, so for now I think it shouldn't be a part of this PR.

2021-11-04 12:05 UTC, mkolesnik approved these changes

2021-11-04 12:07 UTC, mkolesnik commented on .github/workflows/e2e-full.yml
> +          - k8s_version: '1.19'
Yes but it's not "rely on GHAs to not run them multiple times" but rather the way GHA is meant to work. You can read it on their manual.

You can add extra parameters this way to an existing job, it won't duplicate it.

In our case we're not adding anything so it just keeps that one job there as is, it won't duplicate it either way.

2021-11-08 18:50 UTC, merged