Upgrade cloud-prepare and adjust
submariner-io/submariner-operator pull request #1662
Opened 2021-11-16 10:09 UTC by skitt

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-11-16 13:05 UTC, tpantelis requested changes

2021-11-16 13:05 UTC, tpantelis commented on go.mod
> +	github.com/submariner-io/cloud-prepare v0.12.0-m0.0.20211115085640-9f6a4bc47cf9
We should update this to include https://github.com/submariner-io/cloud-prepare/pull/143 which just got merged - it fixes a significant bug.

2021-11-16 13:49 UTC, tpantelis approved these changes

2021-11-17 20:45 UTC, dfarrell07 approved these changes

2021-11-18 02:32 UTC, merged