Support single node clusters with subctl diagnose
submariner-io/submariner-operator pull request #1677
Opened 2021-11-26 15:23 UTC by sridhargaddam

While running subctl diagnose on single node clusters, certain tests
should be skipped. This PR handles it.

Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-11-29 20:44 UTC, dfarrell07 approved these changes

2021-11-29 21:55 UTC, tpantelis requested changes

2021-11-29 21:55 UTC, tpantelis commented on pkg/subctl/cmd/diagnose/all.go
> +		status.EndWithSuccess("Skipping this check as its a single node cluster.")
```suggestion
		status.EndWithSuccess("Skipping this check as it's a single node cluster.")
```

2021-12-01 22:34 UTC, tpantelis approved these changes

2021-12-02 07:56 UTC, merged