Test all kubeconfig-dependent subctl commands
submariner-io/submariner-operator pull request #1681
Opened 2021-11-30 09:36 UTC by skitt

This ensures that we continue supporting the commands we advertise.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-11-30 12:45 UTC, tpantelis requested changes

2021-11-30 12:45 UTC, tpantelis commented on .github/workflows/subctl.yml
> +  upgrade-e2e:
```suggestion
  test-subctl:
```

2021-11-30 19:19 UTC, dfarrell07 approved these changes
Great test coverage addition, thanks @skitt!

2021-12-03 12:38 UTC, tpantelis approved these changes

2021-12-03 13:05 UTC, merged