Move `join` to new subctl implementation
submariner-io/submariner-operator pull request #1699
Opened 2021-12-10 13:24 UTC by Jaanki

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

2021-12-10 14:40 UTC, skitt requested changes

2021-12-10 14:40 UTC, skitt commented on api/submariner/v1alpha1/servicediscovery_types.go
> +	ClusterDetails   ClusterDetails `json:"cluster_info"`
This is a breaking change. You can share struct components but only by “inheriting” the struct. Any changes made here shouldn’t result in changes to the CRD YAMLs.

2021-12-10 14:40 UTC, skitt commented on api/submariner/v1alpha1/submariner_types.go
> +	BrokerDetails            BrokerDetails        `json:"broker_details"`
Same as above, this is a breaking change, as is the `ClusterDetails` field below.

2022-01-03 22:07 UTC, tpantelis commented
I assume this is superseded by https://github.com/submariner-io/submariner-operator/pull/1726?

2022-01-04 04:36 UTC, closed without merging

2022-01-04 04:36 UTC, Jaanki commented
Closed in favor of https://github.com/submariner-io/submariner-operator/pull/1726