Store the PSK in a secret, and mount it
submariner-io/submariner-operator pull request #1724
Opened 2021-12-23 10:12 UTC by skitt

Signed-off-by: Stephen Kitt <skitt@redhat.com>

2021-12-23 16:34 UTC, dfarrell07 approved these changes

2022-01-04 14:17 UTC, tpantelis requested changes

2022-01-04 14:17 UTC, tpantelis commented on pkg/subctl/operator/secret/ensure.go
> +package secret
In accordance with the new package structure, can we move this to _pkg/secret_ instead?

2022-01-04 14:17 UTC, tpantelis commented on pkg/subctl/cmd/join.go
> +		utils.ExitOnError("Error creating PSK secret for cluster", err)
This will also need to be integrated into the relocated **join** code with https://github.com/submariner-io/submariner-operator/pull/1726.

2022-01-04 16:00 UTC, tpantelis approved these changes

2022-01-04 16:27 UTC, merged