Add RHOS support
submariner-io/submariner-operator pull request #1789
Opened 2022-01-17 22:52 UTC by aswinsuryan

Signed-off-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>

2022-01-20 17:13 UTC, aswinsuryan commented
Depends on -> https://github.com/submariner-io/cloud-prepare/pull/188/

2022-01-24 14:58 UTC, aswinsuryan commented
The test will pass only after submariner-io/cloud-prepare#188 is merged and dependency is updated.

2022-01-24 14:58 UTC, nyechiel commented
Depends on https://github.com/submariner-io/cloud-prepare/pull/188/

2022-01-28 12:49 UTC, sridhargaddam requested changes
Some minor comments, otherwise looks good.

2022-01-28 12:49 UTC, sridhargaddam commented on pkg/subctl/cmd/cloud/cleanup/rhos.go
> +// NewCommand returns a new cobra.Command used to prepare a cloud infrastructure.
```suggestion
// newRHOSCleanupCommand returns a new cobra.Command used to cleanup a cloud infrastructure.
```

2022-01-28 12:49 UTC, sridhargaddam commented on pkg/subctl/cmd/cloud/cleanup/rhos.go
> +		Use:   "rhos",
Just a note (no action required in this pr): We are using generic names like rhos, aws, gcp etc but they work mainly with OCP alone. Probably we should use names to convey that its for OCP on aws/gcp/rhos etc.

2022-01-28 12:49 UTC, sridhargaddam commented on pkg/subctl/cmd/cloud/prepare/rhos.go
> +// NewCommand returns a new cobra.Command used to prepare a cloud infrastructure.
```suggestion
// newRHOSPrepareCommand returns a new cobra.Command used to prepare a cloud infrastructure.
```

2022-01-28 12:49 UTC, sridhargaddam commented on pkg/subctl/cmd/cloud/rhos/rhos.go
> +	// with certain images, the instance is not coming up. Needs to be investigated further.
```suggestion

```

I think this is not applicable to this implementation

2022-01-29 08:45 UTC, sridhargaddam approved these changes

2022-01-29 11:11 UTC, tpantelis requested changes

2022-01-29 11:11 UTC, tpantelis commented on pkg/subctl/cmd/cloud/cleanup/rhos.go
> +	utils.ExitOnError("Failed to cleanup RHOS cloud", err)
Let's use the new API in _github.com/submariner-io/submariner-operator/internal/exit_. Please change all other places as well.

```suggestion
	exit.OnErrorWithMessage("Failed to cleanup RHOS cloud", err)
```

2022-01-29 11:11 UTC, tpantelis commented on pkg/subctl/cmd/cloud/rhos/rhos.go
> +	}
```suggestion
```

2022-01-29 11:11 UTC, tpantelis commented on pkg/subctl/cmd/cloud/rhos/rhos.go
> +	command.Flags().StringVar(&cloudEntry, cloudEntryFlag, "", " the cloud entry to use")
```suggestion
	command.Flags().StringVar(&cloudEntry, cloudEntryFlag, "", "the cloud entry to use")
```

2022-02-16 21:57 UTC, tpantelis approved these changes

2022-02-17 01:48 UTC, merged