Move pkg/subctl/resource to internal/
submariner-io/submariner-operator pull request #1799
Opened 2022-01-24 14:31 UTC by Jaanki

This PR moves:
1. pkg/subctl/resource/exec.go -> internal/pods/exec.go
2. pkg/subctl/resource/schedule_pod.go -> internal/pods/schedule.go
3. functions from pkg/subctl/resource/util.go -> internal/nodes/nodes.go

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-01-24 16:36 UTC, tpantelis requested changes

2022-01-24 16:36 UTC, tpantelis commented on internal/pods/schedule.go
> +}
newline.

2022-01-24 16:36 UTC, tpantelis commented on internal/pods/schedule.go
>  type NetworkPod struct {
How about:

```suggestion
type Scheduled struct {
```

2022-01-24 16:36 UTC, tpantelis commented on internal/pods/schedule.go
> +func ScheduleAwaitCompletion(config *Config) (string, error) {
```suggestion
func ScheduleAndAwaitCompletion(config *Config) (string, error) {
```

2022-01-24 18:38 UTC, tpantelis requested changes

2022-01-24 18:38 UTC, tpantelis commented on internal/nodes/nodes.go
> +
Looks like an extraneous change.

2022-01-25 08:55 UTC, Jaanki commented on internal/nodes/nodes.go
> +
yes.

2022-01-25 09:47 UTC, Jaanki commented on pkg/subctl/cmd/gather/cni.go
> +	ovnMasterpods, err := findPods(info.ClientSet, ovnMasterPodLabelOCP)
This was changed becasue golint complains of shadow variable declaration `pods` of package `pods`

2022-01-25 13:02 UTC, tpantelis approved these changes

2022-01-31 21:42 UTC, dfarrell07 approved these changes

2022-02-01 03:25 UTC, merged