Copy export to its own package
submariner-io/submariner-operator pull request #1817
Opened 2022-02-01 09:32 UTC by Jaanki

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-02-01 16:22 UTC, skitt requested changes

2022-02-01 16:22 UTC, skitt commented on pkg/service/export.go
> +	status := cli.NewReporter()
This should be provided as an argument to `Export()` (so that non-CLI users can use the function).

2022-02-01 16:22 UTC, skitt commented on pkg/service/export.go
> +	autil "github.com/submariner-io/admiral/pkg/util"
This import alias isn’t necessary, there are no longer any other `util` packages used here.

2022-02-01 16:26 UTC, tpantelis requested changes

2022-02-01 16:26 UTC, tpantelis commented on pkg/service/export.go
> +			return errors.New("Service already exported")
This isn't an error. 

```suggestion
                         status.Success("Service already exported")
			return nil
```

2022-02-01 16:26 UTC, tpantelis commented on pkg/service/export.go
> +func Export(restConfigProducer restconfig.Producer, serviceNamespace, svcName string) error {
We  can't pass `restconfig.Producer` to the public lib functions since it's internal. Pass a `client.Producer` instead.

2022-02-01 16:26 UTC, tpantelis commented on pkg/service/export.go
> +	status := cli.NewReporter()
Pass in the status `reporter.Interface` to the lib functions.

2022-02-01 16:26 UTC, tpantelis commented on pkg/service/export.go
> +	}
This only needs to be done once so I think we should do it in an `init` function and panic on error.

2022-02-01 16:26 UTC, tpantelis commented on pkg/service/export.go
> +	}
We don't really need to dynamically find the GVR since we know that info directly. Hence we don't need to build a `RESTMapper` and thus we don't need a `rest.Config` which simplifies the code. 

```suggestion
        import ""github.com/submariner-io/admiral/pkg/resource"
        ...
	resourceServiceExport, err := resource.ToUnstructured(mcsServiceExport)
	if err != nil {
		return status.Error(err, "Failed to convert to Unstructured")
	}
	
	gvr := &schema.GroupVersionResource{
		Group:    mcsv1a1.GroupVersion.Group,
		Version:  mcsv1a1.GroupVersion.Version,
		Resource: "serviceexports",
	}
```

2022-02-02 14:38 UTC, tpantelis requested changes
Looks good - just one more minor comment.

2022-02-02 14:38 UTC, tpantelis commented on cmd/subctl/export.go
> +    exit.AndPanicOnError(err)
My previous comment suggested to panic but we really don't need to - we can just do `exit.OnErrorWithMessage`.

2022-02-02 16:15 UTC, Jaanki commented on cmd/subctl/export.go
> +    exit.AndPanicOnError(err)
I like `panic` better. But its not used at any other place so removing it and using `exit.OnErrorWithMessage`

2022-02-02 16:42 UTC, tpantelis requested changes

2022-02-02 16:42 UTC, tpantelis commented on cmd/subctl/export.go
> +	exit.OnError(err)
```suggestion
	exit.OnErrorWithMessage(err)
```

2022-02-02 16:45 UTC, skitt requested changes
Minor change on top of Tom’s request.

2022-02-02 16:45 UTC, skitt commented on cmd/subctl/export.go
> +	// Using Install as AddToScheme is deprecated.
This isn’t necessary as a code comment; it’s explaining a change so it should go in the commit message.

2022-02-03 12:31 UTC, tpantelis approved these changes

2022-02-03 12:45 UTC, skitt approved these changes

2022-02-03 12:45 UTC, merged