Operator container
submariner-io/submariner-operator pull request #1860
Opened 2022-02-21 14:13 UTC by Jaanki

2022-02-21 14:15 UTC, Jaanki commented on pkg/subctl/operator/submarinerop/deployment/ensure.go
> +								AllowPrivilegeEscalation: &[]bool{false}[0],
Change this to new pointer implementation once https://github.com/submariner-io/submariner-operator/pull/1859 is merged.

```suggestion
								AllowPrivilegeEscalation: &[]bool{false}[0],
```

2022-02-21 15:26 UTC, skitt requested changes

2022-02-21 15:26 UTC, skitt commented on pkg/subctl/operator/submarinerop/deployment/ensure.go
> +								AllowPrivilegeEscalation: boolPointer(false),
It turns out there’s a K8s library we can use, `k8s.io/utils/pointer`; see https://github.com/submariner-io/submariner-operator/pull/1859

2022-02-21 17:00 UTC, skitt approved these changes

2022-02-21 18:33 UTC, dfarrell07 approved these changes

2022-02-22 09:02 UTC, sridhargaddam approved these changes

2022-02-22 09:03 UTC, merged