Move uninstall command to new subctl implementation
submariner-io/submariner-operator pull request #1980
Opened 2022-03-24 09:58 UTC by Jaanki

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-03-31 13:17 UTC, tpantelis approved these changes

2022-03-31 13:25 UTC, tpantelis requested changes

2022-03-31 13:25 UTC, tpantelis commented on cmd/subctl/uninstall.go
> +)
To keep these separate from other command vars, let's encapsulate them into a struct:

```suggestion
var uninstallOptions struct {
	noPrompt bool
	namespace string
}
```

2022-04-06 18:12 UTC, Jaanki commented on cmd/subctl/uninstall.go
> +)
Done

2022-04-06 18:24 UTC, tpantelis approved these changes

2022-04-06 19:31 UTC, dfarrell07 commented
If this "moves" the command, shouldn't it be removed from where it was before? Is that planned for later?

2022-04-06 20:03 UTC, dfarrell07 approved these changes

2022-04-06 22:04 UTC, tpantelis commented
> If this "moves" the command, shouldn't it be removed from where it was before? Is that planned for later?

yeah it will be once the rest of the commands are "moved".

2022-04-06 22:32 UTC, merged