subctl show versions displays the output twice
submariner-io/submariner-operator pull request #1991
Opened 2022-03-30 01:18 UTC by tpantelis

Fixes https://github.com/submariner-io/submariner-operator/issues/1990

2022-03-30 04:12 UTC, Jaanki approved these changes

2022-03-30 06:35 UTC, maayanf24 approved these changes

2022-03-30 07:08 UTC, skitt requested changes
I know I’m nit-picking, but could we have a better commit message? Instead of describing the bug, describe the change.

2022-03-30 20:36 UTC, dfarrell07 approved these changes

2022-04-01 09:31 UTC, skitt approved these changes

2022-04-01 10:38 UTC, merged