Define separate structs for each platform options
submariner-io/submariner-operator pull request #2013
Opened 2022-04-12 17:07 UTC by Jaanki

and make prepareaws return error.

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-05-02 05:59 UTC, vthapar approved these changes, later dismissed

2022-05-03 10:17 UTC, skitt requested changes

2022-05-03 10:17 UTC, skitt commented on pkg/subctl/cmd/cloud/prepare/aws.go
> +var config *cloudaws.Config
This needs to declare the instance itself, not just a pointer to it:

```suggestion
var config cloudaws.Config
```

Then whenever you need to pass `config` around, pass a pointer to it, `&config`.

2022-05-03 12:05 UTC, tpantelis requested changes

2022-05-03 12:05 UTC, tpantelis commented on pkg/cloud/aws/aws.go
> +func RunOnAWS(restConfigProducer restconfig.Producer, config Config, status reporter.Interface,
```suggestion
func RunOn(restConfigProducer restconfig.Producer, config Config, status reporter.Interface,
```

2022-05-03 12:05 UTC, tpantelis commented on pkg/cloud/cleanup/aws.go
> +func Aws(restConfigProducer *restconfig.Producer, status reporter.Interface) error {
```suggestion
func AWS(restConfigProducer *restconfig.Producer, status reporter.Interface) error {
```

2022-05-03 12:05 UTC, tpantelis commented on pkg/cloud/prepare/aws.go
> +func Aws(restConfigProducer *restconfig.Producer, ports cloud.Ports, config aws.Config, status reporter.Interface) error {
```suggestion
func AWS(restConfigProducer *restconfig.Producer, ports cloud.Ports, config aws.Config, status reporter.Interface) error {
```

2022-05-03 13:07 UTC, tpantelis approved these changes

2022-05-03 14:36 UTC, skitt approved these changes

2022-05-03 14:36 UTC, merged