Feature branch update
submariner-io/submariner-operator pull request #2022
Opened 2022-04-18 13:51 UTC by Billy99

Merge devel into feature-multi-active-gw.

Also removed:
a7d50c0853975c0c773db345972d0caa45137171 Add support for `subctl join ... --multi-active-gateway=true` (#1951)
It contained an accidental rebase as well as the new code. It will be remerged onto of the top of the rebase.

2022-04-18 14:55 UTC, astoycos approved these changes

2022-04-18 15:04 UTC, anfredette approved these changes
lgtm

2022-04-18 15:21 UTC, anfredette requested changes
Unapproving -- need to rework this.

2022-04-19 14:50 UTC, anfredette commented
This is replaced by https://github.com/submariner-io/submariner-operator/pull/2025 and https://github.com/submariner-io/submariner-operator/pull/2026

2022-04-19 14:50 UTC, closed without merging