Separate system tests out of E2E
submariner-io/submariner-operator pull request #2104
Opened 2022-06-13 14:20 UTC by mkolesnik

This PR separates the system tests out of E2E, making E2E super simple and system tests more focused.

As part of this work the E2E tests have also been improved somewhat.

Please see individual commits for more details.

2022-06-13 16:27 UTC, dfarrell07 commented on .github/workflows/system.yml
> +name: System tests
This ends up showing in the UI of all PRs, and currently it's Leading Caps in all workflows in all repos I think. Would be good to be consistent.

```suggestion
name: System Tests
```

Also, I wonder if anyone has a suggestion for a more descriptive workflow/job name than "System Tests/Test"? I get the idea, but it took some thinking and I authored a lot of these tests. :stuck_out_tongue_winking_eye: A more verbose job name maybe? /me is struggling to think of a good suggestion, will follow up if I think of one

2022-06-14 05:47 UTC, mkolesnik commented on .github/workflows/system.yml
> +name: System tests
Updated the caps, I'm not married to the name if you have a better suggestion I don't mind changing it

2022-06-14 21:34 UTC, dfarrell07 approved these changes

2022-06-16 13:25 UTC, tpantelis commented on .github/workflows/system.yml
> +name: System tests
Unfortunately only the job name is displayed in the branch settings tab so having that more descriptive helps. I suggest job name "_Deployment Test_", so full  name "_System Tests/Deployment Test_".

2022-06-22 14:39 UTC, tpantelis requested changes

2022-06-22 14:39 UTC, tpantelis commented on .github/workflows/system.yml
> +    name: Test
Unfortunately only the job name is displayed in the branch settings tab so having that more descriptive helps. I suggest job name "_Deployment Test_", so full name "_System Tests/Deployment Test_".

```suggestion
    name: Deployment Test
```

2022-06-29 16:21 UTC, tpantelis approved these changes

2022-06-29 19:19 UTC, dfarrell07 commented
> Error: two kubecontexts must be specified

2022-06-30 07:14 UTC, mkolesnik commented
> > Error: two kubecontexts must be specified

Right, I was foolishly trying to avoid parsing the settings file to get the clusters :)

I amended the necessary commit to add code to parse the settings properly, and while at it squashed another commit (the rename) into the one above it.

The PR is otherwise unchanged.

2022-06-30 10:11 UTC, skitt approved these changes

2022-06-30 10:12 UTC, merged