fix in diagnose cluster permissions: add getting deployments and namespaces
submariner-io/submariner-operator pull request #2157
Opened 2022-07-22 21:59 UTC by tomer-shefler

fixing: https://github.com/submariner-io/subctl/issues/129

2022-08-08 07:27 UTC, mkolesnik requested changes
The change is good but please update the commit message with **why** it's needed, e.g. "The diagnose needs get/list capability for namespaces to ..."

2022-08-08 19:49 UTC, dfarrell07 commented
> The change is good but please update the commit message with **why** it's needed, e.g. "The diagnose needs get/list capability for namespaces to ..."

https://submariner.io/development/code-review/#document-why-in-commit-messages

2022-08-15 07:35 UTC, mkolesnik commented
Please make sure to follow the commit message formatting  - https://submariner.io/development/code-review/#commit-message-formatting

2022-08-16 07:43 UTC, mkolesnik requested changes

2022-08-16 07:43 UTC, mkolesnik commented on pkg/embeddedyamls/yamls.go
> +      - namespaces
This file is auto generated, you should be editing the source file `config/rbac/submariner-diagnose/role.yaml`

2022-08-23 12:44 UTC, mkolesnik approved these changes
Thanks

You need to shorten the commit title as it's too long, otherwise it's LGTM :)
https://github.com/submariner-io/submariner-operator/runs/7973475250?check_suite_focus=true#step:3:73

Apparently the lines are too long also.

You can run `make gitlint` locally before pushing the updated commit to make sure it's passing

2022-08-30 11:38 UTC, tpantelis approved these changes

2022-08-30 14:19 UTC, merged