diagnose clusterrole: remove pods sections:
submariner-io/submariner-operator pull request #2169
Opened 2022-08-14 08:58 UTC by tomer-shefler

all pods operations are being done in submariner-operator namespace
and thus these permessions are no longer required on the cluster role
scope

Signed-off-by: Tomer Shefler <sheflertomer@gmail.com>

2022-08-14 11:27 UTC, tomer-shefler commented
solves https://github.com/submariner-io/subctl/issues/48

2022-08-16 07:42 UTC, mkolesnik requested changes

2022-08-16 07:42 UTC, mkolesnik commented on pkg/embeddedyamls/yamls.go
> -  - apiGroups:  # pods are created to run firewall diagnostics
This file is auto generated, you should be editing the source file `config/rbac/submariner-diagnose/cluster_role.yaml`

2022-08-16 07:43 UTC, skitt commented
Thanks for submitting this! `pkg/embeddedyamls/yamls.go` is generated, please make this change in `config/rbac/submariner-diagnose/cluster_role.yaml` too (and then run `make pkg/embeddedyamls/yamls.go`).

Please fix your commit message too:

> Commit e3ba4af3d1:
> 1: T3 Title has trailing punctuation (:): "diagnose clusterrole: remove pods sections:"
> 2: B4 Second line is not empty: "all pods operations are being done in submariner-operator namespace"

2022-08-16 07:45 UTC, skitt commented
This would break `subctl diagnose --namespace …` for any namespace other than the operator namespace (perhaps we should remove that option).

2022-08-16 08:25 UTC, mkolesnik commented
> This would break `subctl diagnose --namespace …` for any namespace other than the operator namespace (perhaps we should remove that option).

We can leave the flag but document it, e.g. that when running diagnose the account used needs to have access to creating/deleting pods on the namespace if it's not the default one.

However, I think removing it is simplest as it doesn't add much value.
I think it was added to support custom operator namespace, but a more robust solution is to auto detect the operator namespace and use it for the diagnosis, without bothering the user.

2022-08-21 14:45 UTC, tomer-shefler commented
> > This would break `subctl diagnose --namespace …` for any namespace other than the operator namespace (perhaps we should remove that option).
> 
> We can leave the flag but document it, e.g. that when running diagnose the account used needs to have access to creating/deleting pods on the namespace if it's not the default one.
> 
> However, I think removing it is simplest as it doesn't add much value. I think it was added to support custom operator namespace, but a more robust solution is to auto detect the operator namespace and use it for the diagnosis, without bothering the user.

So, the desicion is that this namespace option shloud be remained. However a user who wants to use a different namespace should take care of all of the RBACs required to do so.

2022-08-22 05:13 UTC, mkolesnik approved these changes
> So, the desicion, as I understantd it, is that this namespace option shloud be remained. However a user who wants to use a different namespace should take care of all of the RBACs required to do so?

For me its fine as long as you add the details to the website documentation.
I'm also open for entirely removing the namespace option.

@skitt - WDYT?

2022-09-08 06:25 UTC, mkolesnik approved these changes

2022-09-08 13:21 UTC, mkolesnik commented
@tomer-shefler make sure to generate the embedded yamls correctly, currently its failing the CI

2022-09-08 13:36 UTC, tpantelis approved these changes

2022-09-08 14:29 UTC, merged