Add health and readyness probes
submariner-io/submariner-operator pull request #2230
Opened 2022-09-06 11:54 UTC by Jaanki

and use the new ctrl.NewManager, which is an alias of manager.Manager to
create the manager.

Various options are defined at
https://godocs.io/sigs.k8s.io/controller-runtime/pkg/manager#Options.

Health and readyness logic is not implemented yet but are added for
future usage.

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-09-06 12:51 UTC, skitt approved these changes

2022-09-07 02:42 UTC, Jaanki commented on main.go
> +// nolint:gocyclo // No further refactors necessary
@skitt I have added this ignore `gocyclo` lint after your +1. So if you can reapprove.

2022-09-07 14:35 UTC, tpantelis requested changes

2022-09-07 14:35 UTC, tpantelis commented on main.go
> +			"Enabling this will ensure there is only one active controller manager.")
Why do we need these as CLI params and how would we set them?

2022-09-07 14:35 UTC, tpantelis commented on main.go
> +		LeaderElectionID:       "2a1e5b0d.submariner.io",
Where did the magic number "2a1e5b0d" come from?

2022-09-07 14:35 UTC, tpantelis commented on main.go
> +		log.Error(err, "unable to set up ready check")
```suggestion
		log.Error(err, "unable to set up ready check")
		os.Exit(1)
```

2022-09-07 16:26 UTC, Jaanki commented on main.go
> +			"Enabling this will ensure there is only one active controller manager.")
These are needed if we want to customised `health-probe-bind-address` or enable leader election for controller manager. These can be set during runtime like this

`go run main.go --probeAddr 8082`

Again this is an used code added for future use.

2022-09-07 16:28 UTC, Jaanki commented on main.go
> +		LeaderElectionID:       "2a1e5b0d.submariner.io",
Thats autogenerated. Its explanation from official doc

```
// LeaderElectionID determines the name of the resource that leader election
// will use for holding the leader lock.
LeaderElectionID string
```

2022-09-07 16:33 UTC, tpantelis commented on main.go
> +		LeaderElectionID:       "2a1e5b0d.submariner.io",
OK - can you add a comment explaining this?

2022-09-08 10:22 UTC, Jaanki commented on main.go
> +		LeaderElectionID:       "2a1e5b0d.submariner.io",
Done

2022-09-08 11:45 UTC, tpantelis approved these changes

2022-09-08 18:47 UTC, merged