Add GlobalIngressIPs cluster role privs for submariner-diagnose
submariner-io/submariner-operator pull request #2288
Opened 2022-10-17 15:36 UTC by tpantelis

`subctl diagnose` needs to be able to retrieve `GlobalIngressIPs` in any namespace.

Needed by https://github.com/submariner-io/subctl/pull/240.

2022-10-17 15:42 UTC, skitt requested changes
This needs

    make pkg/embeddedyamls/yamls.go

2022-10-17 16:00 UTC, tpantelis commented
> This needs
> 
> ```
> make pkg/embeddedyamls/yamls.go
> ```

Can't believe I forgot that

2022-10-17 16:11 UTC, skitt approved these changes

2022-10-20 05:15 UTC, vthapar approved these changes

2022-10-20 08:16 UTC, merged