Release notes for
submariner-io/submariner-operator pull request #2323
Opened 2022-11-03 09:48 UTC by Jaanki

https://github.com/submariner-io/enhancements/issues/81

Signed-off-by: Janki Chhatbar <jchhatba@redhat.com>

2022-11-03 09:52 UTC, skitt requested changes
I thought we’d said the Operator SDK changes didn’t need release notes, since they’re not user-visible. Has that changed?

2022-11-03 09:54 UTC, Jaanki commented
I wasn't aware of this decision. Anyways, I think the path change for APIs should be mentioned. It could be used by other projects.

2022-11-03 10:30 UTC, skitt requested changes

2022-11-03 10:30 UTC, skitt commented on release-notes/20221103-operator-sdk-upgrade.md
> +* Submariner-operator APIs are converted to single-group. Meaning, API definitions can now be found under `api/`.
```suggestion
* The project was rebuilt using Operator SDK version 1.23.0.
* The operator APIs have been converted to single-group; projects depending on these will need to
  replace `github.com/submariner-io/submariner-operator/api/submariner/v1alpha1` with
  `github.com/submariner-io/submariner-operator/api/v1alpha1` in their imports.
```

2022-11-03 10:31 UTC, skitt commented
> I wasn't aware of this decision. Anyways, I think the path change for APIs should be mentioned. It could be used by other projects.

Fair enough, let’s describe the impact explicitly.

2022-11-03 11:43 UTC, tpantelis commented
> > I wasn't aware of this decision. Anyways, I think the path change for APIs should be mentioned. It could be used by other projects.
> 
> Fair enough, let’s describe the impact explicitly.

Also discussing this on slack. We've stated and agreed in the past that RNs are for end users. A Go API change is not for end user. We've many Go API changes in the past sans RN. Let's stay consistent.

2022-11-04 12:53 UTC, tpantelis commented
> Also discussing this on slack. We've stated and agreed in the past that RNs are for end users. A Go API change is not for end users. We've many Go API changes in the past sans RN. Let's stay consistent.

As a follow-up, to notify possible users of the **submariner-operator** project of the API change, we could add a note to the project release tag once that's created.

2022-11-04 12:54 UTC, closed without merging