Remove duplicate gateway pod RBAC
submariner-io/submariner-operator pull request #2336
Opened 2022-11-10 17:50 UTC by dfarrell07

The submariner-gateway RBAC for pods duplicates the get permission, as it's granted * elsewhere.

This was recently modified in #2214 and #2008.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2022-11-10 18:07 UTC, dfarrell07 commented
@skitt How did you determine in #2008 that pods didn't need some permissions? Just looking at the code?

@tpantelis How did you spot the error in #2225, as it didn't seem to fail CI?

I ask because I don't know if pods really needs *, or if we can get away with a subset.

2022-11-10 19:12 UTC, tpantelis commented
> How did you spot the error in https://github.com/submariner-io/submariner-operator/pull/2225, as it didn't seem to fail CI?

It did fail CI according to the PR summary.

2022-11-11 09:33 UTC, dfarrell07 commented
> > How did you spot the error in #2225, as it didn't seem to fail CI?
> 
> It did fail CI according to the PR summary.

Ah okay, I see. I actually linked to the wrong PR there, this is the gateway which was PR #2214. But still, the point is that it should have failed CI on the PR that made the change, not have been merged.

2022-11-11 14:55 UTC, tpantelis commented
> 
> Ah okay, I see. I actually linked to the wrong PR there, this is the gateway which was PR #2214. But still, the point is that it should have failed CI on the PR that made the change, not have been merged.

It changed the RBAC yaml and the associated Go file but those are used by `subctl`  so they won't take effect until the Go dependency version for **submariner-operator** is updated in the **subctl** repo. This is a side-effect of splitting out the **subctl** repo.

2022-11-11 18:43 UTC, dfarrell07 commented
> > Ah okay, I see. I actually linked to the wrong PR there, this is the gateway which was PR #2214. But still, the point is that it should have failed CI on the PR that made the change, not have been merged.
> 
> It changed the RBAC yaml and the associated Go file but those are used by `subctl` so they won't take effect until the Go dependency version for **submariner-operator** is updated in the **subctl** repo. This is a side-effect of splitting out the **subctl** repo.

Thanks for clarifying Tom, that makes sense.

2022-11-15 18:47 UTC, tpantelis approved these changes

2022-12-17 14:01 UTC, sridhargaddam approved these changes

2023-01-02 15:36 UTC, skitt requested changes
I would rather move in the other direction: instead of removing explicit permissions which are subsumed by wildcard permissions, remove the wildcard permissions and explicitly list all the permissions we really need (ideally, auto-generated from code comments).

2023-01-10 14:03 UTC, dfarrell07 commented
Closing in favor of https://github.com/submariner-io/submariner-operator/issues/1105

2023-01-18 15:19 UTC, closed without merging