Bump sigs.k8s.io/controller-runtime from 0.13.1 to 0.14.0
submariner-io/submariner-operator pull request #2412
Opened 2022-12-16 15:45 UTC by tpantelis

...which provides K8s v0.26 support.

2022-12-16 15:50 UTC, skitt approved these changes

2023-01-05 16:03 UTC, dfarrell07 approved these changes

2023-01-06 15:09 UTC, skitt requested changes

2023-01-06 15:09 UTC, skitt commented on go.mod
> -// Until controller-runtime releases with v0.26 support
Please update the commit message to match what this commit is doing now (dropping the replace, not upgrading to controller-runtime 0.14.0).

2023-01-09 13:25 UTC, skitt approved these changes

2023-01-09 13:25 UTC, merged