Bump submariner version and update globalnet CRDs
submariner-io/submariner-operator pull request #2577
Opened 2023-04-01 11:30 UTC by tpantelis

...to pickup the changes for the status subresource.

2023-04-01 17:47 UTC, vthapar commented
Thanks for this @tpantelis This shows the fixes work. Now we just need to get other PRs in.

2023-04-03 03:34 UTC, sridhargaddam approved these changes

2023-04-03 05:36 UTC, sridhargaddam requested changes
@tpantelis thanks for working on the fix. I'd like to collect some feedback from skitt, so requesting changes.

@skitt, we have an equivalent PR on the devel (under review), but I guess @tpantelis wanted to try if the changes are working on 0.15 so pushed this PR directly on release-0.15 branch. I'd like to hear from you if we can merge this in the current state or if you prefer the devel PR to be merged and then backported to release-0.15 branch.

2023-04-03 07:56 UTC, sridhargaddam commented
Talking to @skitt on slack, he was okay with the PR.

2023-04-03 07:56 UTC, sridhargaddam approved these changes

2023-04-03 07:58 UTC, skitt approved these changes

2023-04-03 09:01 UTC, merged