Verify broker-admin secret in system tests
submariner-io/submariner-operator pull request #2602
Opened 2023-04-19 06:47 UTC by Jaanki

...instead of broker-client secret as is currently done because with https://github.com/submariner-io/subctl/pull/653, subctl no longer creates a broker client SA and its associated secret.

2023-04-19 06:59 UTC, skitt approved these changes

2023-04-19 07:05 UTC, skitt requested changes, later dismissed
You also need to change line 16.

I’m wondering whether we shouldn’t just drop this test — it retrieves the same `ca.crt` twice and compares the result, which isn’t useful. Alternatively, we can get the admin token in `SUBMARINER_BROKER_CA`, then compare each `cluster1` client token.

2023-04-19 12:32 UTC, tpantelis approved these changes

2023-04-19 12:34 UTC, tpantelis commented
Since it's `subctl` that creates these secrets, perhaps these tests should be in the **subctl** project.

2023-04-20 11:59 UTC, sridhargaddam approved these changes

2023-04-20 11:59 UTC, merged

2023-04-20 12:19 UTC, nyechiel commented
Do we need this in 0.15? I am not sure why it's part of the 0.16 board

2023-04-20 12:49 UTC, tpantelis commented
> Do we need this in 0.15?

No this is related to https://github.com/submariner-io/subctl/pull/653.