Bump helm from 3.12.1 to 3.14.1 for CVE-2024-25620
submariner-io/submariner-operator pull request #2970
Opened 2024-02-16 04:12 UTC by dfarrell07

Update generated by:

```
go get -u helm.sh/helm/v3@v3.14.1
go mod tidy
```

Issue identified by a Dependabot alert (#2968) on devel.

2024-02-16 09:34 UTC, skitt requested changes
Please redo this without `-u` to reduce the amount of churn. See https://github.com/submariner-io/shipyard/pull/1555#issuecomment-1948029416 for details.

2024-02-19 16:30 UTC, dfarrell07 commented
Redid without `-u`, but I don't think that changed anything. Also didn't remove the go update this time, as discussed it seems that's caused by the Helm update.

2024-02-19 16:40 UTC, dfarrell07 commented
Could it be a problem to bump the K8s versions in this repo but not other repos on this branch?

2024-02-27 23:56 UTC, tpantelis commented
We decided to ignore the CVE: https://github.com/submariner-io/submariner-operator/pull/2979.

2024-02-27 23:56 UTC, closed without merging