Reduce RBAC permissions for the various components
submariner-io/submariner-operator pull request #3040
Opened 2024-05-02 15:23 UTC by tpantelis

A recent post to the **submariner-security** outlined potential vulnerabilities regarding submariner's RBAC permissions being too broad:

- create/patch/update verb of the statefulsets/replicasets resource
   - A malicious user can create a privileged container with a malicious container image capable of container escape. This would allow him/she gaining ROOT privilege of the worker node the created container deployed. Since the malicious user can control the pod scheduling parameters (e.g., replicas number, node affinity, …), he/she should be able to deploy the malicious container to every (or almost every) worker node. This means the malicious user will be able to control every (or almost every) worker node in the cluster.
   - The other permissions of statefulsets/replicasets/deployments/daemonsets also share the same risks.

In addition, many permissions aren't even used/needed. Also specifying a wildcard for resources and verbs is not best practice - Sonar [flags this](https://sonarcloud.io/project/issues?resolved=false&types=VULNERABILITY&id=submariner-io_submariner-operator&open=AY7GnmQtf1gbRJmNPGKK).

The intent of this PR is to reduce the permissions to only what's needed. See individual commits for details.

Note that for these changes to actually be applied requires updating and rebuilding **subctl**. However, I mirrored the changes in https://github.com/submariner-io/submariner-charts/pull/508 and the E2E in the **submariner-charts** repo directly tests the changes in the PR. So we can be pretty confident the changes are accurate.

2024-05-02 16:20 UTC, aswinsuryan approved these changes

2024-05-02 16:29 UTC, skitt requested changes
This needs some autosquashing ;-).

2024-05-03 12:14 UTC, kaaass approved these changes

2024-05-04 14:54 UTC, tpantelis commented
I added https://github.com/submariner-io/submariner-operator/pull/3040/commits/2691550c7a23ea59f93e98275d0b609cf878834c to eliminate the operator `namespaces` permission.

2024-05-06 07:31 UTC, skitt requested changes
Requesting changes just to make sure the Admiral import is updated to match the merged commit after https://github.com/submariner-io/admiral/pull/905 goes in.

2024-05-06 07:31 UTC, skitt commented on go.mod
> +	github.com/submariner-io/admiral v0.18.0-m3.0.20240504143439-22ee51817b45
This will need to be updated once https://github.com/submariner-io/admiral/pull/905 is merged.

2024-05-06 14:09 UTC, tpantelis commented
> Requesting changes just to make sure the Admiral import is updated to match the merged commit after [submariner-io/admiral#905](https://github.com/submariner-io/admiral/pull/905) goes in.

Done

2024-05-06 14:20 UTC, skitt approved these changes

2024-05-06 14:31 UTC, dfarrell07 approved these changes

2024-05-06 14:32 UTC, merged