Add healthcheck configuration in route agent
submariner-io/submariner-operator pull request #3146
Opened 2024-07-05 16:11 UTC by aswinsuryan

2024-07-18 01:53 UTC, tpantelis commented on config/rbac/submariner-route-agent/role.yaml
> +      - list
We'll need "get" as well.

2024-07-19 01:20 UTC, aswinsuryan commented on config/rbac/submariner-route-agent/role.yaml
> +      - list
Done.

2024-07-19 16:58 UTC, tpantelis requested changes

2024-07-19 16:58 UTC, tpantelis commented on config/rbac/submariner-route-agent/role.yaml
> +      - routeagent
```suggestion
      - routeagents
```

2024-07-19 17:02 UTC, tpantelis commented
I assume we'll be checking `RouteAgent` CRs in `subctl diagnose` so we'll need RBAC permissions [here](https://github.com/submariner-io/submariner-operator/blob/744f41dc3110782089c8cbfd34d1c228973b217c/config/rbac/submariner-diagnose/role.yaml#L35) we well.

2024-07-19 17:33 UTC, aswinsuryan commented
> I assume we'll be checking `RouteAgent` CRs in `subctl diagnose` so we'll need RBAC permissions [here](https://github.com/submariner-io/submariner-operator/blob/744f41dc3110782089c8cbfd34d1c228973b217c/config/rbac/submariner-diagnose/role.yaml#L35) we well.

Done.

2024-07-19 17:33 UTC, aswinsuryan commented on config/rbac/submariner-route-agent/role.yaml
> +      - routeagent
Done

2024-07-19 19:17 UTC, tpantelis approved these changes

2024-07-22 15:43 UTC, dfarrell07 approved these changes

2024-07-22 17:10 UTC, merged