Update CRDs for ClustersetIP fields
submariner-io/submariner-operator pull request #3210
Opened 2024-09-02 07:09 UTC by vthapar

Add fields to CRDs to support ClustersetIPs

Refer: https://github.com/submariner-io/enhancements/pull/230

2024-09-03 17:02 UTC, tpantelis requested changes

2024-09-03 17:02 UTC, tpantelis commented on api/v1alpha1/broker_types.go
> +	ClustersetIPEnabled bool `json:"clustersetIPEnabled,omitempty"`
```suggestion
        // +optional
	ClustersetIPEnabled bool `json:"clustersetIPEnabled,omitempty"`
```

2024-09-03 17:02 UTC, tpantelis commented on api/v1alpha1/broker_types.go
> +	ClustersetIPCIDRRange string `json:"clustersetIPCIDRRange,omitempty"`
```suggestion
        // +optional
	ClustersetIPCIDRRange string `json:"clustersetIPCIDRRange,omitempty"`
```

2024-09-04 12:44 UTC, tpantelis approved these changes

2024-09-06 12:41 UTC, aswinsuryan approved these changes

2024-09-06 12:53 UTC, merged