Upgrade test
submariner-io/submariner-operator pull request #711
Opened 2020-09-24 13:20 UTC by skitt

2020-09-24 17:27 UTC, skitt commented
The current failure is normal, it verifies the failure which is supposed to be fixed by https://github.com/submariner-io/submariner-operator/pull/708.

2020-09-24 17:37 UTC, mangelajo commented
Just a couple of comments (saving CO2 and CI resources while maximizing the tests)

2020-09-24 17:51 UTC, dfarrell07 commented
> Just a couple of comments (saving CO2 and CI resources while maximizing the tests)

I don't see the comments @mangelajo. :eyes:

2020-09-24 17:52 UTC, dfarrell07 approved these changes

2020-09-24 17:58 UTC, dfarrell07 commented
Would be good to rebase and see the test results with #708 merged.

2020-09-28 12:36 UTC, mangelajo commented
> > Just a couple of comments (saving CO2 and CI resources while maximizing the tests)
> 
> I don't see the comments @mangelajo.

oh my.. never hit the "send review" ... :/

2020-09-28 12:36 UTC, mangelajo commented on .github/workflows/upgrade-e2e.yml
> +        globalnet: ['', 'globalnet']
Or... instead keep it always in? , as it's a more involved feature?

2020-10-19 11:09 UTC, dfarrell07 requested changes

2020-10-19 11:09 UTC, dfarrell07 commented on .github/workflows/upgrade-e2e.yml
> +    tags:
I think we don't want to run tests like this on tags, per https://github.com/submariner-io/submariner/commit/b3f568d90458897ae0d5881008a6064812888c25.

2020-10-19 11:09 UTC, dfarrell07 commented on .github/workflows/upgrade-e2e.yml
> +name: Upgrade tests
```suggestion
name: Upgrade Tests
```

(and maybe put the workflow name at the top of the file)

2020-10-19 11:09 UTC, dfarrell07 commented on .github/workflows/upgrade-e2e.yml
> +  upgrade-e2e:
It would be good to give this job an explicit, more human-designed name.

2020-11-09 08:18 UTC, skitt commented
Done in https://github.com/submariner-io/submariner-operator/pull/778.

2020-11-09 08:18 UTC, closed without merging