Add intra-cluster test to subctl throughput benchmark
submariner-io/submariner-operator pull request #723
Opened 2020-09-30 11:31 UTC by maayanf24

Fixes issue #707

Signed-off-by: Maayan Friedman <maafried@redhat.com>

2020-09-30 15:59 UTC, tpantelis requested changes

2020-09-30 15:59 UTC, tpantelis commented on pkg/subctl/benchmark/throughput.go
> +		framework.By("Performing throughput tests from Gateway pod to Gateway pod")
```suggestion
		framework.By(fmt.Sprintf("Performing throughput tests from Gateway pod on cluster %q to Gateway pod on cluster %q ", clusterAName, clusterBName))
```

2020-09-30 15:59 UTC, tpantelis commented on pkg/subctl/benchmark/throughput.go
> +		framework.By("Performing throughput tests from Non-Gateway pod to Non-Gateway pod")
```suggestion
                framework.By(fmt.Sprintf("Performing throughput tests from Non-Gateway pod on cluster %q to Non-Gateway pod on cluster %q ", clusterAName, clusterBName))
```

2020-09-30 15:59 UTC, tpantelis commented on pkg/subctl/cmd/benchmark.go
>  		Short: "Benchmark throughput between two clusters",
```suggestion
		Short: "Benchmark throughput",
```

2020-09-30 15:59 UTC, tpantelis commented on pkg/subctl/cmd/benchmark.go
>  		Long:  "This command runs throughput tests between two clusters",
```suggestion
		Long:  "This command runs throughput tests within a cluster or between two clusters",
```

2020-09-30 15:59 UTC, tpantelis commented on pkg/subctl/benchmark/throughput.go
> +			ClusterA:            framework.ClusterA,
```suggestion
			ClientCluster:            framework.ClusterA,
```

2020-09-30 15:59 UTC, tpantelis commented on pkg/subctl/benchmark/throughput.go
> +			ClusterB:            framework.ClusterB,
```suggestion
			ServerCluster:            framework.ClusterB,
```

2020-10-01 07:31 UTC, mangelajo reviewed
Seems good in general, I like tpantelis suggestions, please ping me once handled.

2020-10-01 08:32 UTC, mangelajo approved these changes
Looks great now, thanks

2020-10-01 11:42 UTC, sridhargaddam approved these changes
LGTM, thanks @maayanf24

2020-10-01 12:48 UTC, merged