fix: update image pull policy when using image override
submariner-io/submariner-operator pull request #939
Opened 2020-11-29 07:12 UTC by SteveMattar

The `ImagePullPolicy` will be set to the correct value according to the image tag
in case of using `ImageOverride` flag.

Signed-off-by: Steve Mattar <smattar@redhat.com>

2020-11-30 10:43 UTC, skitt requested changes

2020-11-30 10:43 UTC, skitt commented on controllers/servicediscovery/servicediscovery_controller.go
> +func getPullPolicy(submariner *submarinerv1alpha1.ServiceDiscovery, componentImage string) corev1.PullPolicy {
Can’t this be shared?

2020-11-30 12:38 UTC, SteveMattar commented on controllers/servicediscovery/servicediscovery_controller.go
> +func getPullPolicy(submariner *submarinerv1alpha1.ServiceDiscovery, componentImage string) corev1.PullPolicy {
Sure

2020-11-30 15:26 UTC, mangelajo approved these changes

2020-12-01 10:17 UTC, dfarrell07 approved these changes

2021-01-04 14:22 UTC, skitt approved these changes

2021-01-04 15:20 UTC, skitt commented
The CRD linting failure is fixed by https://github.com/submariner-io/submariner-operator/pull/1011.

2021-01-04 15:21 UTC, merged