Setup a networkplugin-syncer deployment for OVNKubernetes
submariner-io/submariner-operator pull request #942
Opened 2020-11-30 15:23 UTC by mangelajo

Signed-off-by: Miguel Angel Ajo <majopela@redhat.com>

2020-11-30 15:44 UTC, skitt requested changes

2020-11-30 15:44 UTC, skitt commented on controllers/submariner/netwokplugin_syncer.go
> +							// FIXME: Should be entrypoint script, find/use correct file for routeagent
Copy-pasta?

2020-11-30 15:44 UTC, skitt commented on controllers/submariner/netwokplugin_syncer.go
> +					// The route agent engine on all nodes, regardless of existing taints
Same here?

2020-11-30 15:44 UTC, skitt commented on controllers/submariner/netwokplugin_syncer.go
> +	routeAgentDaemonSet := &appsv1.Deployment{
This isn’t the route agent, is it?

2020-11-30 19:30 UTC, mangelajo reviewed
thank you @skitt handling those comments.

2020-11-30 19:30 UTC, mangelajo commented on controllers/submariner/netwokplugin_syncer.go
> +	routeAgentDaemonSet := &appsv1.Deployment{
ooops

2020-11-30 19:30 UTC, mangelajo commented on controllers/submariner/netwokplugin_syncer.go
> +							// FIXME: Should be entrypoint script, find/use correct file for routeagent
yupppp

2020-11-30 19:36 UTC, mangelajo commented on controllers/submariner/netwokplugin_syncer.go
> +	routeAgentDaemonSet := &appsv1.Deployment{
Done

2020-11-30 19:36 UTC, mangelajo commented on controllers/submariner/netwokplugin_syncer.go
> +							// FIXME: Should be entrypoint script, find/use correct file for routeagent
Done

2020-11-30 19:36 UTC, mangelajo commented on controllers/submariner/netwokplugin_syncer.go
> +					// The route agent engine on all nodes, regardless of existing taints
Done

2020-11-30 19:39 UTC, mangelajo commented
fixing the conflicts now..

2020-11-30 21:02 UTC, tpantelis approved these changes

2020-12-01 08:31 UTC, skitt approved these changes

2020-12-01 08:52 UTC, merged