Added flag to skip GlobalNet configuration on join.
submariner-io/submariner-operator pull request #972
Opened 2020-12-09 17:13 UTC by renan-campos

Signed-off-by: Renan Campos <rcampos@redhat.com>

2020-12-09 17:21 UTC, skitt requested changes
Thanks for this @renan-campos! We’re trying to make boolean flags consistently “positive”, _i.e._ setting them enables something (see https://github.com/submariner-io/submariner-operator/issues/649); could you please rework this as

    --allocate-globalnet

instead, with a default value of `true`? Users would then use

    --allocate-globalnet=false

to skip allocation.

2020-12-09 17:38 UTC, skitt approved these changes
Thanks!

2020-12-10 17:43 UTC, nyechiel commented on pkg/subctl/cmd/join.go
> +	cmd.Flags().BoolVar(&allocGNet, "allocate-globalnet", true, "Allocate GlobalNet CIDR")
```suggestion
	cmd.Flags().BoolVar(&allocGNet, "allocate-globalnet", true, "Allocate Globalnet CIDR")
```

2020-12-10 17:48 UTC, nyechiel commented
Thanks for working on this, @renan-campos! 

@mangelajo @sridhargaddam IIRC a further discussion is needed to determine if we can support this, and especially if/how we can test this. Adding to our 0.8.1 board so that we can properly review this.

2021-01-10 19:11 UTC, nyechiel commented
bump

2021-01-25 14:37 UTC, mangelajo approved these changes

2021-01-25 14:41 UTC, nyechiel commented
TO DO: document the new flag

2021-01-27 15:06 UTC, nyechiel commented
@mangelajo @tpantelis based on our discussion on this one, we can go ahead and merge it.

2021-01-27 15:20 UTC, tpantelis approved these changes

2021-01-27 15:22 UTC, nyechiel commented
@tpantelis can you handle the docs part, please?

2021-01-27 15:45 UTC, merged